networks:
  easyrsa:
    driver: bridge
    name: easyrsa
    external: false
    internal: false

services:
  easyrsa:
    build:
      context: .
      dockerfile: Dockerfile
    image: peymanhr/easyrsa:1.0
    container_name: easyrsa
    environment:
      API_KEY: ${API_KEY}
    networks:
      - easyrsa
    volumes:
      - ./ca:/ca:rw
      - ./openvpn:/openvpn:rw
    command: "sleep infinity"
