services:
  easyrsa:
    build:
      context: .
      dockerfile: Dockerfile
    image: peymanhr/easyrsa:1.0
    container_name: easyrsa
    network_mode: none
    volumes:
      - ./ca:/ca:rw
      - ./openvpn:/openvpn:rw
    command: "sleep infinity"
